name: Test Streamlit

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Streamlit
        run: |
          curl -I --max-time 30 \
          "https://sonsagecsm-jayc6ngmmn7ddh2azigt3q.streamlit.app/"
