name: Test Streamlit

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test app
        run: |
          curl --max-redirs 0 -sS -D - -o /dev/null \
          "https://sonsagecsm-jayc6ngmmn7ddh2azigt3q.streamlit.app/"
